spring:
  application:
    name: audit-service
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    build:
      enabled: true
    env:
      enabled: true
logging:
  level:
    root: INFO
