springBoot {
    buildInfo()
}

spotless {
    kotlin {
        target("src/**/*.kt")
        ktlint("1.3.1").editorConfigOverride([
            ktlint_standard_filename         : "disabled",
            "ktlint_standard_package-name"   : "disabled",
        ])
    }
}

dependencies {
    implementation("net.logstash.logback:logstash-logback-encoder:7.4")
}

tasks.named("bootJar") {
    archiveFileName.set("app.jar")
}

tasks.named("jar") {
    enabled = false
}

tasks.named("check") {
    dependsOn("spotlessCheck")
}
