spring:
  application:
    name: content-service
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    build:
      enabled: true
    env:
      enabled: true
logging:
  level:
    root: INFO
identity:
  api:
    url: ${IDENTITY_API_URL:http://localhost/api/identity}
catalog:
  api:
    url: ${CATALOG_API_URL:http://localhost/api/catalog}
